namespace Falsus.Providers.Text
{
    /// <summary>
    /// This class represents the configuration object of the <see cref="RegexProvider"/> data provider.
    /// </summary>
    public class RegexProviderConfiguration
    {
        /// <summary>
        /// Gets or sets the regular expression pattern that the values generated by the
        /// provider have to match.
        /// </summary>
        /// <value>A regular expression.</value>
        public string Pattern { get; set; }
    }
}
