name: Falsus Quality Gate

on:
  workflow_dispatch:
  push:
    paths:
    - src/**

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        dotnet-version: ['6.0.x']

    runs-on: ubuntu-latest   # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    # Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # Build the Falsus Engine
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      
    # Execute all unit tests for Falsus Engine
    - name: Execute unit tests
      run: dotnet test --no-restore --verbosity normal
