name: Falsus Quality Gate

on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    - converted_to_draft
    branches:
    - main
    paths:
    - src/**

permissions:
  checks: write
  pull-requests: write

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        dotnet-version: ['6.0.x']

    runs-on: ubuntu-latest   # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore src/Falsus.sln

    - name: Build
      run: dotnet build src/Falsus.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Remove engine test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Engine/TestResults

    - name: Remove data types test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/DataTypes/TestResults

    - name: Remove finance provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Finance/TestResults

    - name: Remove internet provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Internet/TestResults

    - name: Remove location provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Location/TestResults

    - name: Remove person provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Person/TestResults

    - name: Remove system provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Sys/TestResults

    - name: Remove text provider test results
      uses: JesseTG/rm@v1.0.3
      with:
        path: src/Providers/Text/TestResults

    - name: Execute Falsus unit tests
      run: dotnet test src/Engine/Falsus.UnitTests/Falsus.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Engine/TestResults"

    - name: Execute data type provider unit tests
      run: dotnet test src/Providers/DataTypes/Falsus.Providers.DataTypes.UnitTests/Falsus.Providers.DataTypes.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/DataTypes/TestResults" --settings cli/runsettings.xml

    - name: Execute finance provider unit tests
      run: dotnet test src/Providers/Finance/Falsus.Providers.Finance.UnitTests/Falsus.Providers.Finance.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Finance/TestResults" --settings cli/runsettings.xml

    - name: Execute Internet provider unit tests
      run: dotnet test src/Providers/Internet/Falsus.Providers.Internet.UnitTests/Falsus.Providers.Internet.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Internet/TestResults" --settings cli/runsettings.xml

    - name: Execute Location provider unit tests
      run: dotnet test src/Providers/Location/Falsus.Providers.Location.UnitTests/Falsus.Providers.Location.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Location/TestResults" --settings cli/runsettings.xml

    - name: Execute Person provider unit tests
      run: dotnet test src/Providers/Person/Falsus.Providers.Person.UnitTests/Falsus.Providers.Person.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Person/TestResults" --settings cli/runsettings.xml

    - name: Execute Sys provider unit tests
      run: dotnet test src/Providers/Sys/Falsus.Providers.Sys.UnitTests/Falsus.Providers.Sys.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Sys/TestResults" --settings cli/runsettings.xml

    - name: Execute Text provider unit tests
      run: dotnet test src/Providers/Text/Falsus.Providers.Text.UnitTests/Falsus.Providers.Text.UnitTests.csproj --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory "src/Providers/Text/TestResults" --settings cli/runsettings.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          src/Engine/TestResults/*.trx
          src/Providers/DataTypes/TestResults/*.trx
          src/Providers/Finance/TestResults/*.trx
          src/Providers/Internet/TestResults/*.trx
          src/Providers/Location/TestResults/*.trx
          src/Providers/Person/TestResults/*.trx
          src/Providers/Sys/TestResults/*.trx
          src/Providers/Text/TestResults/*.trx

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: src/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
