name: Falsus Quality Gate

on:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    branches:
    - main
    paths:
    - src/**
    
permissions:
  checks: write
  pull-requests: write
  
jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        dotnet-version: ['6.0.x']

    runs-on: ubuntu-latest   # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore src/Falsus.sln

    # Build the Falsus Engine
    - name: Build
      run: dotnet build src/Falsus.sln --configuration ${{ matrix.configuration }} --no-restore

    # Execute all unit tests for Falsus Engine
    - name: Execute unit tests
      run: dotnet test src/Falsus.sln --no-restore --verbosity normal --logger trx --collect:"XPlat Code Coverage" --results-directory ./coverage

    # Publish unit tests results      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          src/**/TestResults/**/*.xml
          src/**/TestResults/**/*.trx
          src/**/TestResults/**/*.json

    # Run Code Coverage
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    # Publish Code Coverage 
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
